sudo: required
dist: trusty

language: haxe

os:
  - linux
  - osx

haxe:
  - "3.2.1"
  - development

matrix:
  allow_failures:
    - haxe: development

install:
  - haxelib install travix
  - haxelib run travix install

script:
  - haxelib run travix interp
  - haxelib run travix neko
  - haxelib run travix python
  - haxelib run travix node
  # - haxelib run travix js
  # - haxelib run travix flash
  # - haxelib run travix java # TOO MANY ERRORS FROM THE JAVA COMPILER :(
  - haxelib run travix cpp
  # - haxelib run travix cs # TOO MANY ERRORS FROM THE C# COMPILER :(
  - haxelib run travix php
